---
cities:
    default:         1
    moscow:          1
    москва:          1
    msk:             1
    мск:             1
    chelyabinsk:    54
    челябинск:      54
    челяба:         54
    члб:            54
    ekaterinburg:   55
    yekaterinburg:  55
    екатеринбург:   55
    екат:           55
    екб:            55
    ekb:            55
    ебург:          55
    е-бург:         55
    ёбург:          55
    miass:         229
    миасс:         229
