---
cities:
    default:         1
    moscow:          1
    msk:             1
    мск:             1
    питер:           2
    спб:             2
    spb:             2
    chelyabinsk:    54
    челяба:         54
    члб:            54
    ekaterinburg:   55
    yekaterinburg:  55
    екат:           55
    екб:            55
    ekb:            55
    ебург:          55
    е-бург:         55
    ёбург:          55
    нск:            81
    nsk:            81
    тагил:         111
    магнитка:      183
    miass:         229

types:
    default:        1
    трамвай:        1
    троллейбус:     2
    тм:             1
    тб:             2
    метрополитен:   3
    метро:          3
    монорельс:      4
    фуникулёр:      5
    фуникулер:      5
    транслор:       6
    мувер:          7
    атн:            7
    маглев:         8
    электробус:     9
    tram:           1
    tramway:        1
    trolleybus:     2
    tm:             1
    tb:             2
    metro:          3
    metropolitain:  3
    subway:         3
    underground:    4
    monorail:       4
    funicular:      5
    translohr:      6
    mover:          7
    maglev:         8
    'electic bus':  9

url:
    cities:     https://transphoto.org/country/1/
    wagons:     https://transphoto.org/list.php